# Generated by Django 2.1.7 on 2019-03-29 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('customer', models.CharField(max_length=80)),
                ('status', models.IntegerField(choices=[(1, 'Объявлен'), (2, 'Открыт'), (3, 'Завершён')])),
            ],
        ),
    ]
