# Generated by Django 2.1.7 on 2019-03-31 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arrears',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_order', models.IntegerField()),
                ('name_lain', models.CharField(max_length=200)),
                ('name_ex', models.CharField(max_length=200)),
                ('volume', models.CharField(max_length=50)),
                ('qt', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_order', models.IntegerField()),
                ('tr_num', models.CharField(max_length=200)),
                ('courier', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Liquids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_lain', models.CharField(max_length=200)),
                ('name_ex', models.CharField(max_length=200)),
                ('volume', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Out',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_order', models.IntegerField()),
                ('name_lain', models.CharField(max_length=200)),
                ('name_ex', models.CharField(max_length=200)),
                ('volume', models.CharField(max_length=50)),
                ('qt', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='order',
            old_name='num',
            new_name='num_order',
        ),
    ]
