# Generated by Django 2.1.7 on 2019-03-31 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0002_auto_20190331_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrears',
            name='num_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sklad.Order'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='num_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sklad.Order'),
        ),
        migrations.AlterField(
            model_name='out',
            name='num_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sklad.Order'),
        ),
    ]
