# Generated by Django 2.1.7 on 2019-03-31 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0003_auto_20190331_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='out',
            name='include',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='arrears',
            name='name_lain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sklad.Liquids'),
        ),
        migrations.AlterField(
            model_name='order',
            name='num_order',
            field=models.IntegerField(verbose_name='Номер заказа'),
        ),
    ]
