# Generated by Django 2.1.7 on 2019-03-31 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0004_auto_20190331_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arrears',
            name='name_lain',
        ),
        migrations.RemoveField(
            model_name='arrears',
            name='num_order',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Объявлен'), (2, 'Открыт'), (3, 'Завершён')], default=1),
        ),
        migrations.AlterField(
            model_name='out',
            name='num_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outs', to='sklad.Order'),
        ),
        migrations.DeleteModel(
            name='Arrears',
        ),
    ]
