# Generated by Django 2.1.7 on 2019-04-01 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0005_auto_20190331_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='sum_delivery',
            field=models.FloatField(default=0, verbose_name='Стоимость доставки'),
        ),
        migrations.AddField(
            model_name='liquids',
            name='price',
            field=models.FloatField(default=0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='courier',
            field=models.CharField(max_length=100, verbose_name='Куртерска служба'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='tr_num',
            field=models.CharField(max_length=200, verbose_name='Трек-номер'),
        ),
        migrations.AlterField(
            model_name='liquids',
            name='name_ex',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='liquids',
            name='name_lain',
            field=models.CharField(max_length=200, verbose_name='Линейка'),
        ),
        migrations.AlterField(
            model_name='liquids',
            name='volume',
            field=models.CharField(max_length=50, verbose_name='Объём'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.CharField(max_length=80, verbose_name='Заказчик'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Объявлен'), (2, 'Открыт'), (3, 'Завершён')], default=1, verbose_name='Статус заказа'),
        ),
        migrations.AlterField(
            model_name='out',
            name='include',
            field=models.BooleanField(default=False, verbose_name='Отправляем?'),
        ),
        migrations.AlterField(
            model_name='out',
            name='name_ex',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='out',
            name='name_lain',
            field=models.CharField(max_length=200, verbose_name='Линейка'),
        ),
        migrations.AlterField(
            model_name='out',
            name='num_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outs', to='sklad.Order', verbose_name='Номер заказа'),
        ),
        migrations.AlterField(
            model_name='out',
            name='qt',
            field=models.IntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='out',
            name='volume',
            field=models.CharField(max_length=50, verbose_name='Объём'),
        ),
    ]
