# Generated by Django 2.1.7 on 2019-04-02 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0006_auto_20190401_2103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courier_name', models.CharField(default='', max_length=100, verbose_name='Курьерская служба')),
                ('phone', models.CharField(max_length=15, verbose_name='Телефон')),
            ],
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='courier',
        ),
        migrations.AddField(
            model_name='delivery',
            name='courier_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sklad.Courier'),
            preserve_default=False,
        ),
    ]
