# Generated by Django 2.1.7 on 2019-04-03 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0007_auto_20190402_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='out',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
