# Generated by Django 2.1.7 on 2019-04-05 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0008_auto_20190403_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='название')),
            ],
            options={
                'verbose_name': 'линейка',
                'verbose_name_plural': 'линейки',
            },
        ),
        migrations.AlterModelOptions(
            name='courier',
            options={'verbose_name': 'курьерская служба', 'verbose_name_plural': 'курьерские службы'},
        ),
        migrations.AlterModelOptions(
            name='delivery',
            options={'verbose_name': 'доставка', 'verbose_name_plural': 'доставки'},
        ),
        migrations.AlterModelOptions(
            name='liquids',
            options={'verbose_name': 'жидкость', 'verbose_name_plural': 'жидкости'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'заказ', 'verbose_name_plural': 'заказы'},
        ),
        migrations.AlterModelOptions(
            name='out',
            options={'verbose_name': 'партия', 'verbose_name_plural': 'партии'},
        ),
        migrations.RemoveField(
            model_name='out',
            name='name_lain',
        ),
        migrations.AlterField(
            model_name='courier',
            name='courier_name',
            field=models.CharField(default='', max_length=100, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='courier_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sklad.Courier', verbose_name='Курьер'),
        ),
        migrations.AlterField(
            model_name='liquids',
            name='name_lain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sklad.Lain', verbose_name='линейка'),
        ),
    ]
