# Generated by Django 2.1.7 on 2019-04-05 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0011_auto_20190405_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liquids',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Цена'),
        ),
    ]
